version: "3.8"

services:
  app:
    # PHP-FPM
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - app

  web:
    image: nginx:1.24
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybookshelf
      MYSQL_USER: bookshelf
      MYSQL_PASSWORD: bookshelf
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

    networks:
      - app

networks:
  app: 

volumes:
  db_data:
