INSERT INTO livros (id_usuario, titulo, autores, numero_paginas, genero, nacional, capa_path, editora, descricao) VALUES
(1, 'Percy Jackson e o Ladrão de Raios', 'Rick Riordan', 377, 'Fantasia', 'N', 'uploads/placeholder.png', 'Intrínseca', 'Um garoto descobre ser filho de um deus grego e embarca em aventuras.'),
(1, 'O Hobbit', 'J.R.R. Tolkien', 310, 'Fantasia', 'N', 'uploads/placeholder.png', 'HarperCollins', 'A jornada de Bilbo Bolseiro para recuperar um tesouro roubado.'),
(1, '1984', 'George Orwell', 328, 'Distopia', 'N', 'uploads/placeholder.png', 'Companhia das Letras', 'Um futuro sombrio de vigilância e controle total.'),
(1, 'Dom Casmurro', 'Machado de Assis', 256, 'Clássico', 'S', 'uploads/placeholder.png', 'Editora Ática', 'Romance sobre ciúmes e dúvidas na vida de Bentinho.'),
(1, 'Grande Sertão: Veredas', 'João Guimarães Rosa', 496, 'Romance', 'S', 'uploads/placeholder.png', 'Editora Nova Fronteira', 'Narrativa épica sobre jagunços no sertão brasileiro.'),
(1, 'O Pequeno Príncipe', 'Antoine de Saint-Exupéry', 96, 'Fábula', 'N', 'uploads/placeholder.png', 'Agir', 'Um príncipe viaja por planetas e aprende lições de vida.'),
(1, 'Cem Anos de Solidão', 'Gabriel García Márquez', 417, 'Realismo Mágico', 'N', 'uploads/placeholder.png', 'Record', 'Saga da família Buendía na cidade fictícia de Macondo.'),
(1, 'A Revolução dos Bichos', 'George Orwell', 112, 'Satírico', 'N', 'uploads/placeholder.png', 'Companhia das Letras', 'Fábula que critica regimes totalitários.'),
(1, 'Memórias Póstumas de Brás Cubas', 'Machado de Assis', 210, 'Clássico', 'S', 'uploads/placeholder.png', 'Editora Ática', 'Narrado por um defunto, conta sua vida e reflexões.'),
(1, 'O Alquimista', 'Paulo Coelho', 197, 'Ficção', 'S', 'uploads/placeholder.png', 'Rocco', 'Viagem de autodescoberta de um pastor em busca de seu sonho.'),
(1, 'Harry Potter e a Pedra Filosofal', 'J.K. Rowling', 223, 'Fantasia', 'N', 'uploads/placeholder.png', 'Rocco', 'O início da saga do jovem bruxo em Hogwarts.'),
(1, 'O Senhor dos Anéis: A Sociedade do Anel', 'J.R.R. Tolkien', 423, 'Fantasia', 'N', 'uploads/placeholder.png', 'HarperCollins', 'Formação da sociedade para destruir o anel do poder.'),
(1, 'Sapiens: Uma Breve História da Humanidade', 'Yuval Noah Harari', 498, 'Não-ficção', 'N', 'uploads/placeholder.png', 'L&PM', 'Resumo da história da humanidade e suas transformações.'),
(1, 'O Código Da Vinci', 'Dan Brown', 489, 'Suspense', 'N', 'uploads/placeholder.png', 'Arqueiro', 'Mistério envolvendo segredos históricos e simbologia.'),
(1, 'A Menina que Roubava Livros', 'Markus Zusak', 552, 'Drama', 'N', 'uploads/placeholder.png', 'Intrínseca', 'História de uma jovem na Alemanha nazista.'),
(1, 'Ensaio Sobre a Cegueira', 'José Saramago', 312, 'Drama', 'N', 'uploads/placeholder.png', 'Companhia das Letras', 'Uma epidemia de cegueira repentina abala a sociedade.'),
(1, 'O Nome do Vento', 'Patrick Rothfuss', 656, 'Fantasia', 'N', 'uploads/placeholder.png', 'Arqueiro', 'A jornada do jovem Kvothe para se tornar uma lenda.'),
(1, 'Capitães da Areia', 'Jorge Amado', 272, 'Romance', 'S', 'uploads/placeholder.png', 'Companhia das Letras', 'Meninos de rua sobrevivem em Salvador com astúcia e coragem.'),
(1, 'A Metamorfose', 'Franz Kafka', 104, 'Ficção', 'N', 'uploads/placeholder.png', 'Antofágica', 'Homem acorda transformado em inseto e enfrenta o absurdo.'),
(1, 'Quincas Borba', 'Machado de Assis', 240, 'Clássico', 'S', 'uploads/placeholder.png', 'Editora Ática', 'Filósofo excêntrico deixa fortuna e cão para um amigo.'),
(1, 'It: A Coisa', 'Stephen King', 1104, 'Terror', 'N', 'uploads/placeholder.png', 'Suma', 'Grupo enfrenta entidade maligna que assombra cidade por décadas.'),
(1, 'O Silmarillion', 'J.R.R. Tolkien', 480, 'Fantasia', 'N', 'uploads/placeholder.png', 'HarperCollins', 'Histórias da criação do mundo de Tolkien.'),
(1, 'Auto da Compadecida', 'Ariano Suassuna', 123, 'Comédia', 'S', 'uploads/placeholder.png', 'Nova Fronteira', 'Dois nordestinos se envolvem em confusões cômicas e religiosas.'),
(1, 'Orgulho e Preconceito', 'Jane Austen', 416, 'Romance', 'N', 'uploads/placeholder.png', 'Penguin Companhia', 'Clássico sobre relações sociais e amor na Inglaterra georgiana.'),
(1, 'Admirável Mundo Novo', 'Aldous Huxley', 312, 'Distopia', 'N', 'uploads/placeholder.png', 'Biblioteca Azul', 'Sociedade futurista sob controle genético e condicionamento.'),
(1, 'O Diário de Anne Frank', 'Anne Frank', 240, 'Biografia', 'N', 'uploads/placeholder.png', 'Record', 'Relato tocante de uma jovem escondida durante o Holocausto.'),
(1, 'Torto Arado', 'Itamar Vieira Junior', 264, 'Romance', 'S', 'uploads/placeholder.png', 'Todavia', 'Irmãs enfrentam as dores e lutas do sertão baiano.'),
(1, 'Morte e Vida Severina', 'João Cabral de Melo Neto', 76, 'Poema dramático', 'S', 'uploads/placeholder.png', 'Nova Fronteira', 'Poesia sobre a seca e o sofrimento do nordestino.'),
(1, 'A Máquina do Tempo', 'H.G. Wells', 152, 'Ficção Científica', 'N', 'uploads/placeholder.png', 'Zahar', 'Cientista viaja ao futuro e vê o destino da humanidade.'),
(1, 'A Ilha Misteriosa', 'Júlio Verne', 512, 'Aventura', 'N', 'uploads/placeholder.png', 'Zahar', 'Náufragos descobrem segredos em uma ilha inexplorada.'); 
